package consys.onlineexam.helper;

import android.annotation.SuppressLint;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class AppConstant {
    public static String App_type = new String();
    public static String DB_NAME = "manthandb.sqlite";
    public static String DB_PATH = (StorageUtils.getpathCorrect() + "/");
    public static String MY_PATH = (DB_PATH + "android_LangINconfig3/" + DB_NAME);
    public static String Server_Phone_No;
    public static String Server_SMS_Receiver;
    public static long TIMEOUT = 5000;
    public static String WiFIName = "LiveExam";
    public static ArrayList<String> adlist = new ArrayList();
    public static String answered_string = new String();
    public static String attended_string = new String();
    public static int back_count = 0;
    public static boolean back_flag = false;
    public static String contact1;
    public static String contact2;
    public static String contact3;
    public static boolean copy_flag = false;
    public static ArrayList correct_ans = new ArrayList();
    public static boolean data_check_flag = false;
    public static long daytime = 0;
    public static ArrayList<ExamModel> elist = new ArrayList();
    public static float exam_time = 0.0f;
    @SuppressLint({"SdCardPath"})
    public static String file = (DB_PATH + "android_LangINconfig3/m.cs");
    public static String file_name = (DB_PATH + "android_LangINconfig3/.manthan.cs");
    public static boolean flag_n = false;
    public static boolean flag_start = true;
    public static boolean flag_start2 = true;
    public static String image_dir;
    public static boolean insertion_flag = false;
    public static String jsonDailyQuotes = (DB_PATH + "android_LangINconfig3/DailyQuote.cs");
    public static String key = "consistentsystem";
    public static int last_exam_id = 0;
    public static HashMap<Integer, Float> mapMarks = new HashMap();
    public static HashMap<Integer, ArrayList> mapcorrectans = new HashMap();
    public static HashMap<Integer, ArrayList> mapuserans = new HashMap();
    public static float marks_percentage = 0.0f;
    public static float negative_marks = 0.0f;
    public static String news_data = (DB_PATH + "android_LangINconfig3/NewsOpni.html");
    public static String news_date;
    public static ArrayList<NewsModel> newslist;
    public static String notification;
    public static Object obj;
    public static float obtainedMarks = 0.0f;
    public static int qcount = 0;
    public static List<Integer> qlist;
    public static String question_key = "onlineExamKey@#123";
    public static boolean r_flag = true;
    public static boolean resultview = false;
    public static String selected_chapter;
    public static String selected_exam;
    public static String selected_exam1 = "";
    public static String selected_subject = "";
    public static String selected_test;
    public static int selected_test_Id;
    public static String serverURLForNews = "http://consistentsystem.com/AppGateway/compt/manthan/manthanNews_noti";
    public static String serverURLForQuotes = "http://consistentsystem.com/AppGateway/compt/Apti/Quotes.txt";
    public static String server_mail = "contact@consistentsystem.com";
    public static String server_url;
    public static int solved_question = 0;
    public static StudentModel student = new StudentModel();
    public static String study_chapter;
    public static String study_subject;
    public static HashMap<String, ArrayList<ChapterModel>> sub_exam_list_map = new HashMap();
    public static ArrayList<String> sublist = new ArrayList();
    public static String tip_date;
    public static ArrayList<TipModel> tiplist;
    public static float totalMarks = 0.0f;
    public static int total_questions = 0;
    public static ArrayList<ExamModel> updatelist = new ArrayList();
    public static ArrayList<Integer> user_ans = new ArrayList();
    public static String version_file_name = (DB_PATH + "android_LangINconfig3/.manthan_version.txt");
}
